<?php
/**
 * $Id: xoops_version.php,v 1.4 2003/10/26 08:28:42 wellwine Exp $
 * Copyright (c) 2003 by Jeremy N. Cowgar <jc@cowgar.com>
 * Copyright (c) 2003 by Hiro SAKAI (http://wellwine.net/)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting
 * source code which is considered copyrighted (c) material of the
 * original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
 */
$modversion['name'] = _MI_WEBALIZER_NAME;
$modversion['version'] = 0.2;
$modversion['description'] = _MI_WEBLOG_DESC;
$modversion['author'] = 'Dave Tauzell';
$modversion['credits'] = 'Xoops System';
$modversion['help'] = 'webalizer_help.html';
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/webalizer_slogo.png';
$modversion['dirname'] = 'webalizer';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = 'webalizer_prefs';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Config Options
$modversion['config'][1]['name'] = 'webalizer_out_dir';
$modversion['config'][1]['title'] = '_MI_WEBALIZER_OUT_DIR';
$modversion['config'][1]['description'] = '_MI_WEBALIZER_OUT_DIRDESC';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = 'cache/usage';

$modversion['config'][2]['name'] = 'webalizer_start';
$modversion['config'][2]['title'] = '_MI_WEBALIZER_START';
$modversion['config'][2]['description'] = '_MI_WEBALIZER_STARTDESC';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = 'index.html';

/*
$modversion['config'][2]['name'] = 'dateformat';
$modversion['config'][2]['title'] = '_MI_WEBLOG_DATEFORMAT';
$modversion['config'][2]['description'] = '_MI_WEBLOG_DATEFORMATDSC';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = 'Y/m/d';

$modversion['config'][3]['name'] = 'timeformat';
$modversion['config'][3]['title'] = '_MI_WEBLOG_TIMEFORMAT';
$modversion['config'][3]['description'] = '_MI_WEBLOG_TIMEFORMATDSC';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = 'g:i a';

$modversion['config'][4]['name'] = 'update_reads_when';
$modversion['config'][4]['title'] = '_MI_WEBLOG_UPDATE_READS_WHEN';
$modversion['config'][4]['description'] = '_MI_WEBLOG_UPDATE_READS_WHENDSC';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 1;
$modversion['config'][4]['options'] = array('_MI_WEBLOG_UPDATE_READS_WHEN1'=>1,
                                            '_MI_WEBLOG_UPDATE_READS_WHEN2'=>2,
                                            '_MI_WEBLOG_UPDATE_READS_WHEN3'=>3);

$modversion['config'][5]['name'] = 'showavatar';
$modversion['config'][5]['title'] = '_MI_WEBLOG_SHOWAVATAR';
$modversion['config'][5]['description'] = '_MI_WEBLOG_SHOWAVATARDSC';
$modversion['config'][5]['formtype'] = 'yesno';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 1;

$modversion['config'][6]['name'] = 'minentrysize';
$modversion['config'][6]['title'] = '_MI_WEBLOG_MINENTRYSIZE';
$modversion['config'][6]['description'] = '_MI_WEBLOG_MINENTRYSIZEDSC';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 75;

$modversion['config'][7]['name'] = 'editorheight';
$modversion['config'][7]['title'] = '_MI_WEBLOG_EDITORHEIGHT';
$modversion['config'][7]['description'] = '_MI_WEBLOG_EDITORHEIGHTDSC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 20;

$modversion['config'][8]['name'] = 'editorwidth';
$modversion['config'][8]['title'] = '_MI_WEBLOG_EDITORWIDTH';
$modversion['config'][8]['description'] = '_MI_WEBLOG_EDITORWIDTHDSC';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 70;

$modversion['config'][9]['name'] = 'adminonly';
$modversion['config'][9]['title'] = '_MI_WEBLOG_ONLYADMIN';
$modversion['config'][9]['description'] = '_MI_WEBLOG_ONLYADMINDSC';
$modversion['config'][9]['formtype'] = 'yesno';
$modversion['config'][9]['valuetype'] = 'int';
$modversion['config'][9]['default'] = 0;

// wellwine for read cookie begins
$modversion['config'][10]['name'] = 'expiration';
$modversion['config'][10]['title'] = '_MI_WEBLOG_EXPIRATION';
$modversion['config'][10]['description'] = '_MI_WEBLOG_EXPIRATIONDSC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 86400;

// wellwine for rss feed
$modversion['config'][11]['name'] = 'rssshow';
$modversion['config'][11]['title'] = '_MI_WEBLOG_RSSSHOW';
$modversion['config'][11]['description'] = '_MI_WEBLOG_RSSSHOWDSC';
$modversion['config'][11]['formtype'] = 'yesno';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = 1;

$modversion['config'][12]['name'] = 'rssmax';
$modversion['config'][12]['title'] = '_MI_WEBLOG_RSSMAX';
$modversion['config'][12]['description'] = '_MI_WEBLOG_RSSMAXDSC';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 10;

$modversion['config'][13]['name'] = 'imgurl';
$modversion['config'][13]['title'] = '_MI_WEBLOG_IMGURL';
$modversion['config'][13]['description'] = '_MI_WEBLOG_IMGURLDSC';
$modversion['config'][13]['formtype'] = 'textbox';
$modversion['config'][13]['valuetype'] = 'text';
$modversion['config'][13]['default'] = XOOPS_URL.'/images/logo.gif';

*/

// Templates

// Search
$modversion['hasSearch'] = 0;

//Blocks
/*
$modversion['blocks'][1]['file'] = 'weblog_recent.php';
$modversion['blocks'][1]['name'] = _MI_WEBLOG_RECENT_BNAME1;
$modversion['blocks'][1]['description'] = _MI_WEBLOG_RECENT_BNAME1_DESC;
$modversion['blocks'][1]['show_func'] = 'b_weblog_recent_show';
$modversion['blocks'][1]['edit_func'] = 'b_weblog_recent_edit';
$modversion['blocks'][1]['template'] = 'weblog_block_recent.html';
$modversion['blocks'][1]['options'] = '10|25|Y/m/d|1|1|1';

$modversion['blocks'][2]['file'] = 'weblog_recent.php';
$modversion['blocks'][2]['name'] = _MI_WEBLOG_TOP_WEBLOGS;
$modversion['blocks'][2]['description'] = _MI_WEBLOG_TOP_WEBLOGS_DESC;
$modversion['blocks'][2]['show_func'] = 'b_weblog_top_weblogs_show';
$modversion['blocks'][2]['edit_func'] = 'b_weblog_top_weblogs_edit';
$modversion['blocks'][2]['template'] = 'weblog_block_top_weblogs.html';
$modversion['blocks'][2]['options'] = '10|1|1';
*/

// Menu
$modversion['hasMain'] = 1;

// Smarty
$modversion['use_smarty'] = 1;

// Comments
$modversion['hasComments'] = 0;

// Notifications
$modversion['hasNotification'] = 0;
